#!/bin/bash

set -v

# (re)create empty DB

dropdb cmetal
sudo -u postgres dropuser cmetal 
sudo -u postgres createuser -d cmetal
createdb cmetal

# create tables

psql -d cmetal -f ./sql/create-tables.sql
